import Head from "next/head"

const DocumentHead = () => {
  return (
    <Head>
      <title>Rock, Paper, Scissors</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />
    </Head>
  )
}

export default DocumentHead
