import Head from 'next/head'

const DocumentHead = () => {
	return (
		<Head>
			<title>Rock, Paper, Scissors</title>
			<meta name="description" content="Generated by create next app" />
			<meta
				name="viewport"
				content="width=device-width, initial-scale=1.0"
			/>
			<link rel="icon" href="/favicon.png" />
		</Head>
	)
}

export default DocumentHead
